package com.example.ui.screens

import androidx.compose.animation.*
import androidx.compose.animation.core.tween
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.*
import com.example.ui.components.SubScreenAppBar
import com.example.ui.theme.*
import com.example.viewmodel.CareerViewModel

@Composable
fun AnalysisScreen(
  viewModel: CareerViewModel,
  onNavigateToRoadmap: () -> Unit,
  onBackClick: () -> Unit
) {
  val analysis by viewModel.analysisState.collectAsState()
  val resumeState by viewModel.resumeState.collectAsState()
  val scrollState = rememberScrollState()
  val context = androidx.compose.ui.platform.LocalContext.current

  Scaffold(
    topBar = {
      SubScreenAppBar(
        title = "Resume Analysis",
        onBackClick = onBackClick
      )
    },
    containerColor = BrandBackground
  ) { paddingValues ->
    Box(
      modifier = Modifier
        .fillMaxSize()
        .padding(paddingValues)
        .background(BrandBackground)
    ) {
      Column(
        modifier = Modifier
          .fillMaxSize()
          .verticalScroll(scrollState)
          .padding(horizontal = 20.dp, vertical = 20.dp),
        verticalArrangement = Arrangement.spacedBy(24.dp)
      ) {
        // Screen Header
        Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
          Text(
            text = "Resume Analysis",
            style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold,
            color = Color.White
          )
          Text(
            text = "Actionable vector intelligence generated by VersaCareer AI.",
            style = MaterialTheme.typography.labelMedium,
            color = BrandSecondaryText
          )
        }

        // Check selection status
        if (analysis.isRealSelected) {
          Card(
            modifier = Modifier.fillMaxWidth().testTag("real_resume_selected_card"),
            colors = CardDefaults.cardColors(containerColor = BrandCardBg),
            shape = RoundedCornerShape(24.dp),
            border = BorderStroke(1.dp, Color(0xFF334155))
          ) {
            Column(
              modifier = Modifier.padding(24.dp),
              horizontalAlignment = Alignment.CenterHorizontally,
              verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
              Box(
                modifier = Modifier
                  .size(72.dp)
                  .background(AccentGreen.copy(alpha = 0.1f), CircleShape),
                contentAlignment = Alignment.Center
              ) {
                Icon(
                  imageVector = Icons.Default.CheckCircle,
                  contentDescription = null,
                  tint = AccentGreen,
                  modifier = Modifier.size(36.dp)
                )
              }

              Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(4.dp)
              ) {
                Text(
                  text = "Resume Selected Successfully",
                  color = Color.White,
                  style = MaterialTheme.typography.titleLarge,
                  fontWeight = FontWeight.Bold,
                  textAlign = TextAlign.Center
                )
                Text(
                  text = "Your document is prepared in application state. Status: Ready for Analysis.",
                  color = BrandSecondaryText,
                  style = MaterialTheme.typography.bodyMedium,
                  textAlign = TextAlign.Center,
                  lineHeight = 20.sp
                )
              }

              Box(
                modifier = Modifier
                  .fillMaxWidth()
                  .height(1.dp)
                  .background(Color(0xFF334155))
              )

              Column(
                modifier = Modifier.fillMaxWidth(),
                verticalArrangement = Arrangement.spacedBy(10.dp)
              ) {
                Row(
                  modifier = Modifier.fillMaxWidth(),
                  horizontalArrangement = Arrangement.SpaceBetween
                ) {
                  Text("File Name", color = BrandSecondaryText, style = MaterialTheme.typography.bodyMedium)
                  Text(analysis.fileName, color = Color.White, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Bold)
                }
                Row(
                  modifier = Modifier.fillMaxWidth(),
                  horizontalArrangement = Arrangement.SpaceBetween
                ) {
                  Text("File Size", color = BrandSecondaryText, style = MaterialTheme.typography.bodyMedium)
                  Text(analysis.fileSize, color = Color.White, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Bold)
                }
                Row(
                  modifier = Modifier.fillMaxWidth(),
                  horizontalArrangement = Arrangement.SpaceBetween
                ) {
                  Text("Upload Status", color = BrandSecondaryText, style = MaterialTheme.typography.bodyMedium)
                  Text("Ready for Analysis", color = AccentGreen, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Bold)
                }
                Row(
                  modifier = Modifier.fillMaxWidth(),
                  horizontalArrangement = Arrangement.SpaceBetween
                ) {
                  Text("Format", color = BrandSecondaryText, style = MaterialTheme.typography.bodyMedium)
                  val ext = if (analysis.fileName.endsWith(".docx", ignoreCase = true)) "Word Document (DOCX)" else "Portable Document Format (PDF)"
                  Text(ext, color = BrandSecondary, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Bold)
                }
              }
            }
          }

          if (analysis.isError) {
            Card(
              modifier = Modifier.fillMaxWidth().testTag("error_card"),
              colors = CardDefaults.cardColors(containerColor = BrandCardBg),
              shape = RoundedCornerShape(24.dp),
              border = BorderStroke(1.dp, AccentRed)
            ) {
              Column(
                modifier = Modifier.padding(24.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(16.dp)
              ) {
                Box(
                  modifier = Modifier
                    .size(72.dp)
                    .background(AccentRed.copy(alpha = 0.1f), CircleShape),
                  contentAlignment = Alignment.Center
                ) {
                  Icon(
                    imageVector = Icons.Default.Error,
                    contentDescription = null,
                    tint = AccentRed,
                    modifier = Modifier.size(36.dp)
                  )
                }
                Text(
                  "AI Analysis Failed",
                  color = Color.White,
                  style = MaterialTheme.typography.titleLarge,
                  fontWeight = FontWeight.Bold
                )
                Text(
                  "There was an error parsing your resume with the Gemini AI engine. Please verify your Internet connection and your API key settings, then try again.",
                  color = BrandSecondaryText,
                  style = MaterialTheme.typography.bodyMedium,
                  textAlign = TextAlign.Center,
                  lineHeight = 20.sp
                )
                Button(
                  onClick = { viewModel.triggerAnalysis(context) },
                  colors = ButtonDefaults.buttonColors(containerColor = BrandPrimary),
                  shape = RoundedCornerShape(12.dp)
                ) {
                  Icon(Icons.Default.Refresh, contentDescription = null, tint = Color.White)
                  Spacer(modifier = Modifier.width(8.dp))
                  Text("Retry Analysis Evaluation", color = Color.White, fontWeight = FontWeight.Bold)
                }
              }
            }
          } else if (resumeState.status == UploadStatus.ANALYZING) {
            Card(
              modifier = Modifier.fillMaxWidth().testTag("analyzing_card"),
              colors = CardDefaults.cardColors(containerColor = BrandCardBg),
              shape = RoundedCornerShape(24.dp),
              border = BorderStroke(1.dp, BrandPrimary)
            ) {
              Column(
                modifier = Modifier.padding(24.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(16.dp)
              ) {
                CircularProgressIndicator(
                  color = BrandPrimary,
                  modifier = Modifier.size(48.dp)
                )
                Text(
                  "Connecting to Gemini...",
                  color = Color.White,
                  style = MaterialTheme.typography.titleMedium,
                  fontWeight = FontWeight.Bold
                )
                Text(
                  "Evaluating core tech stacked alignment, ATS compatibility factors, and engineering growth trajectories in real time.",
                  color = BrandSecondaryText,
                  style = MaterialTheme.typography.bodyMedium,
                  textAlign = TextAlign.Center,
                  lineHeight = 18.sp
                )
              }
            }
          } else if (analysis.isAnalysisAvailable) {
            Card(
              modifier = Modifier.fillMaxWidth().testTag("analysis_results_card"),
              colors = CardDefaults.cardColors(containerColor = BrandCardBg),
              shape = RoundedCornerShape(24.dp),
              border = BorderStroke(1.dp, Color(0xFF334155))
            ) {
              Column(
                modifier = Modifier.padding(24.dp),
                verticalArrangement = Arrangement.spacedBy(20.dp)
              ) {
                Row(
                  modifier = Modifier.fillMaxWidth(),
                  horizontalArrangement = Arrangement.SpaceBetween,
                  verticalAlignment = Alignment.CenterVertically
                ) {
                  Column {
                    Text(
                      text = "OVERALL CONGRATULATORY SCORE",
                      style = MaterialTheme.typography.labelSmall,
                      color = BrandPrimary,
                      fontWeight = FontWeight.Bold,
                      letterSpacing = 1.1.sp
                    )
                    Text(
                      text = "${analysis.overallScore} / 100",
                      style = MaterialTheme.typography.headlineLarge,
                      fontWeight = FontWeight.Black,
                      color = Color.White
                    )
                  }
                  
                  Box(
                    contentAlignment = Alignment.Center,
                    modifier = Modifier.size(72.dp)
                  ) {
                    CircularProgressIndicator(
                      progress = { analysis.overallScore / 100f },
                      modifier = Modifier.fillMaxSize(),
                      color = AccentGreen,
                      strokeWidth = 6.dp,
                      trackColor = Color(0xFF0F172A)
                    )
                    Text(
                      text = "${analysis.overallScore}%",
                      style = MaterialTheme.typography.titleSmall,
                      fontWeight = FontWeight.Bold,
                      color = Color.White
                    )
                  }
                }

                Box(
                  modifier = Modifier
                    .fillMaxWidth()
                    .height(1.dp)
                    .background(Color(0xFF334155))
                )

                // Breakdown Subscores
                Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
                  Text(
                    text = "VECTORS OF COMPETENCY EVALUATIONS",
                    style = MaterialTheme.typography.labelSmall,
                    color = BrandSecondary,
                    fontWeight = FontWeight.Bold
                  )
                  ScoreIndicatorColumn("Technical Skills Foundation", analysis.technicalSkillsScore)
                  ScoreIndicatorColumn("Applicant Tracking System (ATS)", analysis.atsCompatibilityScore)
                  ScoreIndicatorColumn("Experience Relevance Weight", analysis.marketRelevanceScore)
                  ScoreIndicatorColumn("Project Quality Depth", analysis.projectQualityScore)
                }

                Box(
                  modifier = Modifier
                    .fillMaxWidth()
                    .height(1.dp)
                    .background(Color(0xFF334155))
                )

                // Key Strengths Card
                if (analysis.strengths.isNotEmpty()) {
                  Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                      Icon(Icons.Default.CheckCircle, contentDescription = null, tint = AccentGreen, modifier = Modifier.size(18.dp))
                      Spacer(modifier = Modifier.width(6.dp))
                      Text("ASTUTE PROFESSIONAL STRENGTHS", style = MaterialTheme.typography.labelSmall, color = AccentGreen, fontWeight = FontWeight.Bold)
                    }
                    analysis.strengths.forEach { strength ->
                      Text("• $strength", style = MaterialTheme.typography.bodySmall, color = Color.White, lineHeight = 16.sp)
                    }
                  }
                }

                // Gaps and Weaknesses
                if (analysis.weaknesses.isNotEmpty()) {
                  Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                      Icon(Icons.Default.Warning, contentDescription = null, tint = BrandSecondary, modifier = Modifier.size(18.dp))
                      Spacer(modifier = Modifier.width(6.dp))
                      Text("PRIORITY AREAS OF IMPROVEMENT", style = MaterialTheme.typography.labelSmall, color = BrandSecondary, fontWeight = FontWeight.Bold)
                    }
                    analysis.weaknesses.forEach { weakness ->
                      Text("• $weakness", style = MaterialTheme.typography.bodySmall, color = Color.White, lineHeight = 16.sp)
                    }
                  }
                }
              }
            }

            // CTA Button to go get targets
            Button(
              onClick = onNavigateToRoadmap,
              modifier = Modifier
                .fillMaxWidth()
                .height(50.dp)
                .testTag("onboarding_roadmap_btn"),
              colors = ButtonDefaults.buttonColors(containerColor = BrandPrimary),
              shape = RoundedCornerShape(12.dp)
            ) {
              Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.Center) {
                Icon(Icons.Default.Map, contentDescription = null, tint = Color.White)
                Spacer(modifier = Modifier.width(8.dp))
                Text("Open Custom Learning Roadmap", color = Color.White, fontWeight = FontWeight.Bold)
              }
            }
          } else {
            Card(
              modifier = Modifier.fillMaxWidth().testTag("not_available_card"),
              colors = CardDefaults.cardColors(containerColor = BrandCardBg),
              shape = RoundedCornerShape(24.dp),
              border = BorderStroke(1.dp, Color(0xFF334155))
            ) {
              Column(
                modifier = Modifier.padding(24.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(16.dp)
              ) {
                Box(
                  modifier = Modifier
                    .size(72.dp)
                    .background(BrandPrimary.copy(alpha = 0.1f), CircleShape),
                  contentAlignment = Alignment.Center
                ) {
                  Icon(
                    imageVector = Icons.Default.Info,
                    contentDescription = null,
                    tint = BrandSecondary,
                    modifier = Modifier.size(36.dp)
                  )
                }
                Text(
                  text = "Analysis not available yet.",
                  color = Color.White,
                  style = MaterialTheme.typography.titleLarge,
                  fontWeight = FontWeight.Bold,
                  textAlign = TextAlign.Center
                )
                Text(
                  text = "Upload and analyze a resume under Upload tab to generate results.",
                  color = BrandSecondaryText,
                  style = MaterialTheme.typography.bodyMedium,
                  textAlign = TextAlign.Center,
                  lineHeight = 20.sp
                )
              }
            }
          }
        } else {
          Card(
            modifier = Modifier.fillMaxWidth(),
            colors = CardDefaults.cardColors(containerColor = BrandCardBg),
            shape = RoundedCornerShape(24.dp),
            border = BorderStroke(1.dp, Color(0xFF334155))
          ) {
            Column(
              modifier = Modifier.padding(24.dp),
              horizontalAlignment = Alignment.CenterHorizontally,
              verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
              Box(
                modifier = Modifier
                  .size(72.dp)
                  .background(BrandPrimary.copy(alpha = 0.1f), CircleShape),
                contentAlignment = Alignment.Center
              ) {
                Icon(
                  imageVector = Icons.Default.CloudUpload,
                  contentDescription = null,
                  tint = BrandSecondary,
                  modifier = Modifier.size(36.dp)
                )
              }

              Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(4.dp)
              ) {
                Text(
                  "No Resume Selected Yet",
                  color = Color.White,
                  style = MaterialTheme.typography.titleLarge,
                  fontWeight = FontWeight.Bold,
                  textAlign = TextAlign.Center
                )
                Text(
                  "Please upload a resume in PDF or DOCX format under the Upload tab to get started with full evaluations.",
                  color = BrandSecondaryText,
                  style = MaterialTheme.typography.bodyMedium,
                  textAlign = TextAlign.Center
                )
              }
            }
          }
        }

        Spacer(modifier = Modifier.height(16.dp))
      }
    }
  }
}

@Composable
fun ScoreIndicatorColumn(title: String, score: Int, modifier: Modifier = Modifier) {
  Column(
    modifier = modifier,
    verticalArrangement = Arrangement.spacedBy(4.dp)
  ) {
    Row(
      modifier = Modifier.fillMaxWidth(),
      horizontalArrangement = Arrangement.SpaceBetween,
      verticalAlignment = Alignment.CenterVertically
    ) {
      Text(
        text = title,
        style = MaterialTheme.typography.bodySmall,
        color = BrandSecondaryText
      )
      Text(
        text = "$score%",
        style = MaterialTheme.typography.labelSmall,
        color = Color.White,
        fontWeight = FontWeight.Bold
      )
    }

    LinearProgressIndicator(
      progress = { score / 100f },
      modifier = Modifier
        .fillMaxWidth()
        .height(5.dp)
        .clip(CircleShape),
      color = BrandSecondary,
      trackColor = Color(0xFF0F172A)
    )
  }
}
